### PR TITLE
docs: Add example usage for network transclusions

### PR DESCRIPTION
**Pull request by josephmturner**
Thank you! This patch isn't ready to merge, please see below.

### CODE REVIEW

**Comment by josephmturner** [comment]
This patch is not ready to merge.  I am about to submit [org-transclusion-http](https://git.sr.ht/~ushin/org-transclusion-http) for review on NonGNU ELPA.  After that, I will work on transclusions via `hyper://`, and I will update this PR to document that functionality also.

Please wait to release `v1.4.0` until the `hyper://` transclusion is published and documented.

Thank you so much @nobiot!!!

**Comment by nobiot** [comment]
No worries :). Thank you for the heads up and all the efforts.

**Comment by nobiot** [comment]
You have been sending several PRs. I am staying put for them. Or should I start merging them?

**Comment by josephmturner** [comment]
Thanks for your patience!

All of the PRs, including this one, are now ready to be merged (#230, #231, #232, #233, #234, #236)

The hyperdrive-org-transclusion feature is almost ready to be merged into the `hyperdrive.el` master branch.  After that, I will release a new version of `hyperdrive.el`.

Please feel free to release a new version of `org-transclusion` when you have time :)

**Comment by josephmturner** [comment]
To clarify my comment above, please merge those pending PRs (if you approve them) _before_ releasing `v1.4.0`.  Thank you!!

**Comment by nobiot** [comment]
Thank you for the clarification. I will get to approving the PRs :) Hopefully today.

**Pull request merged**
