### PR TITLE
Create .gitignore

### PR DESCRIPTION
**Pull request by randomwangran**
Add ignore files for the project clearance.

### CODE REVIEW

**Comment by randomwangran** [comment]
Just a quick follow up with the motivation for this change:

I have your packages installed by git-submodule ([ref](https://emacsair.me/2016/05/17/assimilate-emacs-packages-as-git-submodules/)).

The issue is that I often accidentally added some backup files or left some byte-compile file in the package folder.

This makes tracking the change within my main .emacs project really hard to identify what's going on.

If the user's git dashboard is clean, then it would be super easy to identify the changes over time.

I've attached a figure to show my clutter .emacs magit-status dashboard.

I really don't know how to solve it from my side, so I just did this awkward PR hoping the maintainer could help me.

Thanks for your awesome packages.

image

**Comment by nobiot** [comment]
Sorry I must have overlooked this PR...
But I feel that .gitignore does not have to be shared in a repo. Looking at its content you pushed here, I don’t need it to be in my repo.

I’m not an expert in Git so I must be missing something....

**Comment by nobiot** [comment]
In addition, I don’t know what this subproject thing is in your screen image. Sorry i really have no idea how i might be of any help here.

**Comment by randomwangran** [comment]
Chris Barrett gave me a good suggestion https://github.com/chrisbarrett/skeletor.el/pull/46#issuecomment-761709355 which I can do from my part.

```
*.elc
*~
```

According to [gitignore - Specifies intentionally untracked files to ignore](https://git-scm.com/docs/gitignore), this file with the PR will force the Git to ignore files like:

```
org-transclusion.elc     <<< byte-compiled file
org-transclusion.el~     <<< auto-saved file
```

This subproject thing is in your screen image is `org-transclusion.el~`, which is generated due to changes in the buffer.

I have almost a hundred packages install using `submodule`, and I like to read code in those submodules, so it gradually clutters my magit dashboard. 

I can understand dealing with the file that I am unfamiliar with, I am totally fine with the suggestions from Chris Barrett.

**Comment by nobiot** [comment]
... So... you don't need this PR by the sound of it. Is this correct understanding?

**Comment by randomwangran** [comment]
yes.

**Pull request closed without merging**
